config/routes.rb
ActivitiesFeed::Application.routes.draw do

  match "/activities/feed(/:id)" => "activities#feed"
  match "/activities/display" => "activities#display"
  
  root :to => "activities#index"

  resources :activity_types
  resources :activities

end

app/models/activity.rb
# == Schema Information
# Schema version: 20110120184825
#
# Table name: activities
#
#  id               :integer         not null, primary key
#  message          :string(255)
#  permalink        :string(255)
#  activity_type_id :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class Activity < ActiveRecord::Base
  belongs_to :activity_type
  validates_presence_of :message, :permalink, :activity_type_id
  validates_numericality_of :activity_type_id, :only_integer => true, :greater_than => 0, :message => "does not exist."
  
  @@NUMBER_OF_MOST_RECENT = 5
  
  # Activity uses the id field rather than created_at to determine time
  # ordering since this avoids conversion of times from javascript, and
  # also avoids possible conflicts.
  
  # Return a maximum of @@MAX_TO_FEED of the most recent activities.
  def self.get_most_recent
    order("id DESC").limit(@@NUMBER_OF_MOST_RECENT).includes(:activity_type)
  end
  
  # Return a maximum of @@MAX_TO_FEED of the most recent activities which
  # are more recent than the activity with id "id".
  def self.get_more_recent_than(id)
    where("id > ?", id).order("id DESC").limit(@@NUMBER_OF_MOST_RECENT)
  end
  
end

app/models/activity_type.rb
# == Schema Information
# Schema version: 20110120184825
#
# Table name: activity_types
#
#  id             :integer         not null, primary key
#  name           :string(255)
#  thumbnail_name :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

class ActivityType < ActiveRecord::Base
  has_many :activities
  validates_presence_of :name, :thumbnail_name
  
  def thumbnail_url
    "http://graphics.suite101.com/activity_feed_icon_#{self.thumbnail_name}_32.png"
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  
  caches_action :feed, :expires_in => 1.minute
  caches_action :display
  cache_sweeper :activity_sweeper,:only => [:create, :update, :destroy]
  
  # GET /activities/feed(/:id)
  def feed
    if params[:id]
      @activities = Activity.get_more_recent_than(params[:id])
    else
      @activities = Activity.get_most_recent
    end
    render :layout => false
  end
  
  # GET /activities/display
  def display
    #@activities = Activity.get_most_recent
    render :layout => false
  end 
    
  # GET /activities
  def index
    @activities = Activity.limit(100)
  end

  # GET /activities/1
  def show
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  def create
    @activity = Activity.new

    @activity.message = params[:activity][:message]
    @activity.permalink = params[:activity][:permalink]
    @activity.activity_type = ActivityType.where(:name => params[:activity][:activity_type_name]).first
 
    if @activity.save
      head :created
    else
      head :bad_request
    end
  end
  
  private
  
  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # PUT /activities/1
  def update
    @activity = Activity.find(params[:id])

    @activity.message = params[:activity][:message]
    @activity.permalink = params[:activity][:permalink]
    @activity.activity_type = ActivityType.where(:name =>  params[:activity][:activity_type_name]).first

    if @activity.save
      redirect_to(@activity, :notice => 'Activity was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /activities/1
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to(activities_url)
  end
end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  # GET /activity_types
  # GET /activity_types.xml
  def index
    @activity_types = ActivityType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @activity_types }
    end
  end

  # GET /activity_types/1
  # GET /activity_types/1.xml
  def show
    @activity_type = ActivityType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @activity_type }
    end
  end

  # GET /activity_types/new
  # GET /activity_types/new.xml
  def new
    @activity_type = ActivityType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @activity_type }
    end
  end

  # GET /activity_types/1/edit
  def edit
    @activity_type = ActivityType.find(params[:id])
  end

  # POST /activity_types
  # POST /activity_types.xml
  def create
    @activity_type = ActivityType.new(params[:activity_type])

    respond_to do |format|
      if @activity_type.save
        format.html { redirect_to(@activity_type, :notice => 'Activity type was successfully created.') }
        format.xml  { render :xml => @activity_type, :status => :created, :location => @activity_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @activity_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /activity_types/1
  # PUT /activity_types/1.xml
  def update
    @activity_type = ActivityType.find(params[:id])

    respond_to do |format|
      if @activity_type.update_attributes(params[:activity_type])
        format.html { redirect_to(@activity_type, :notice => 'Activity type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_types/1
  # DELETE /activity_types/1.xml
  def destroy
    @activity_type = ActivityType.find(params[:id])
    @activity_type.destroy

    respond_to do |format|
      format.html { redirect_to(activity_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/activities/_activity.html.erb
<div class="activity">
	<a href="<%= activity.permalink %>" target="_top">
		<%= image_tag(activity.activity_type.thumbnail_url) %>
		<%= activity.message %><br/>
		<span class="time"><%= time_ago_in_words(activity.created_at, true) %> ago.</span>
	</a>
</div>

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= label_tag 'Activity Type' %><br />
    <%= text_field_tag 'activity[activity_type_name]', @activity.activity_type && @activity.activity_type.name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/display.html.erb
<%= stylesheet_link_tag 'rails_activity_feed' %>
<%= javascript_include_tag 'jquery', 'rails', 'application' %>

<div class="rails_activity_feed_box" id="rails_activity_feed_box">
</div>

<script type="text/javascript">	
		
	var UPDATE_INTERVAL_SECONDS = 15;

	update_feed();	
	
	setInterval(function(){
		update_feed();
	}, UPDATE_INTERVAL_SECONDS*1000);

</script>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/feed.html.erb
<%= render @activities %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Permalink</th>
    <th>Activity type</th>
    <th>Created time</th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.message %></td>
    <td><%= activity.permalink %></td>
    <td><%= activity.activity_type.name %></td>
	<td><%= activity.created_at %></td>
    <td><%= link_to 'Show', activity %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @activity.message %>
</p>

<p>
  <b>Permalink:</b>
  <%= @activity.permalink %>
</p>

<p>
  <b>Activity type:</b>
  <%= @activity.activity_type_id %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/activity_types/_form.html.erb
<%= form_for(@activity_type) do |f| %>
  <% if @activity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_type.errors.count, "error") %> prohibited this activity_type from being saved:</h2>

      <ul>
      <% @activity_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :thumbnail_name %><br />
    <%= f.text_field :thumbnail_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_types/edit.html.erb
<h1>Editing activity_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity_type %> |
<%= link_to 'Back', activity_types_path %>

app/views/activity_types/index.html.erb
<h1>Listing activity_types</h1>

<table>
  <tr>
	<th>Thumbnail</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activity_types.each do |activity_type| %>
  <tr>
	<td><%= image_tag activity_type.thumbnail_url %></td>
    <td><%= activity_type.name %></td>
    <td><%= link_to 'Show', activity_type %></td>
    <td><%= link_to 'Edit', edit_activity_type_path(activity_type) %></td>
    <td><%= link_to 'Destroy', activity_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity type', new_activity_type_path %>

app/views/activity_types/new.html.erb
<h1>New activity_type</h1>

<%= render 'form' %>

<%= link_to 'Back', activity_types_path %>

app/views/activity_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Thumbnail:</b>
  <%= image_tag @activity_type.thumbnail_url %>
</p>

<p>
  <b>Name:</b>
  <%= @activity_type.name %>
</p>

<p>
  <b>Thumbnail name:</b>
  <%= @activity_type.thumbnail_name %>
</p>


<%= link_to 'Edit', edit_activity_type_path(@activity_type) %> |
<%= link_to 'Back', activity_types_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActivitiesFeed</title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= javascript_include_tag 'jquery', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>